### ISSUE TITLE
题目扩充问题

### ISSUE THREAD

**Issue by xiaohuIsBest** [ygxiuming/kaoyanzhengzhishuati#1]
想问一下，如果想要之后把肖四肖八，或者其他题目资料生成对应的json/数据库，有现成的脚本吗？

**Comment by ygxiuming** [comment]
> 想问一下，如果想要之后把肖四肖八，或者其他题目资料生成对应的json/数据库，有现成的脚本吗？

我是从苍盾爬的，还真不一定找得到，到时候我看看吧，能更新我就更新。

**Comment by xiaohuIsBest** [comment]
好的，🐮

**Comment by ygxiuming** [comment]
> 想问一下，如果想要之后把肖四肖八，或者其他题目资料生成对应的json/数据库，有现成的脚本吗？

肖4和肖8还有各个模拟卷以及时事政治题库已添加
